config/routes.rb
Rails.application.routes.draw do

  root "categories#index"
  get "/secret/:key" => "articles#edit"
  resources :categories do
    resources :articles
  end

  # get "/categories/:id" => "categories#show"
  # get "/categories" => "categories#index"
  # get "/categories/:category_id/articles/:id" => "articles#show"
  # get "/categories/:category_id/articles/new" => "articles#new"
  # post "/categories/:category_id/articles" => "articles#create"
  # get "/categories/:category_id/articles/:id/edit" => "articles#edit"
  # patch "/categories/:category_id/articles/:id" => "articles#edit"
  # put "/categories/:category_id/articles/:id" => "articles#edit"
  # delete "/categories/:category_id/articles/:id" => "articles#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category

  def key
    key = []
    8.times do
     key << ([*'a'..'z'] + [*'A'..'Z'] + [*0..9]).sample
    end
    key.join
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.url_key = @article.key
    @article.save
    @category = Category.find(params[:category_id])
    @category.articles << @article
    @category.save

    redirect_to edit_category_article_path(@category ,@article)
  end

  def edit
    if params[:key]
    @article = Article.find_by(url_key: params[:key])
    @category = @article.category
    else
    @article = Article.find(params[:id])
    @category = @article.category
    end
  end

  def update
    @article = Article.find_by(url_key: params[:key])
    @article.update(article_params)
    @category = @article.category
    @article.save
    redirect_to category_article_path(@category, @article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    @category = @article.category
    redirect_to category_path(@category)
  end

  private


def article_params
  params.require(:article).permit(:title, :description, :contact, :price)
end





end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<p> Your url key is /secret/<%=@article.url_key %></p><br>
<p> Don't Forget it!!!</p>

<%= form_for [@category, @article] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :desciption %>
  <%= f.text_area :description, size: "40x10" %><br>
  <%= f.label :price %>
  <%= f.number_field :price %><br>
  <%= f.label :contact %>
  <%= f.text_field :contact %><br>

  <%= f.submit %>
  <% end %>

<br><p> Or whatever like delete it!</p>
<%= link_to 'Destroy',  category_article_path(@category, @article),
    data: { confirm: 'Are you sure?' }, method: :delete %>

app/views/articles/new.html.erb
<%= form_for [@category, @article] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :desciption %>
  <%= f.text_area :description, size: "40x10" %><br>
  <%= f.label :price %>
  <%= f.number_field :price %><br>
  <%= f.label :contact %>
  <%= f.text_field :contact %><br>

  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
  <br>
  <br>
<h4><%= @article.description %></h4><br>
<h4><%= @article.contact %></h4><br>
<h4>$<%= @article.price %></h4>

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to("Category: #{category.title}", category_path(category))%></li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<h2>Category: <%= @category.title %></h2>
<%= link_to('create new article', new_category_article_path(@category, @article)) %><br><br>
<% @articles.each do |article| %>
  <%= link_to article.title, category_article_path(@category, article) %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craigslist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>